### ISSUE TITLE
Doesn't treat & as a reserved character

### ISSUE THREAD

**Issue by timbunce** [mithun/perl-uri-encode#2]

**Comment by mithun** [comment]
Can you please provide an example?

**Comment by timbunce** [comment]
Sure:
```
$ perl -MURI::Encode=uri_encode -we 'warn uri_encode("&")'
& at -e line 1.

$ perl -MURI::Escape=uri_escape -we 'warn uri_escape("&")'
%26 at -e line 1.
```

**Comment by mithun** [comment]
Thanks.

This module does not encode/escape reserved characters by default. See [description](https://metacpan.org/pod/URI::Encode#DESCRIPTION)

```
$ perl -MURI::Encode=uri_encode -we 'warn uri_encode("&", { encode_reserved => 1} )'
%26 at -e line 1.

```

**Comment by timbunce** [comment]
Umm. I see that now. That's a very surprising choice! That behaviour means the module behaviour is unsafe by default. That's worth a big bold notice in the docs.
Oh well, We've switched to URI::Escape now.
Thanks for your responsiveness.
