### ISSUE TITLE
Fix typo in manpage

### ISSUE THREAD

**Issue by lucaskanashiro** [mithun/perl-uri-encode#4]
In Debian we are currently applying the following patch to
URI-Encode.
We thought you might be interested in it too.

    Description: Fix typo in manpage
    Author: Lucas Kanashiro <kanashiro.duarte@gmail.com>
    Last-Updated: 2016-05-03
    

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/liburi-encode-perl.git/plain/debian/patches/0001_fix-typo-in-manpage.patch

Thanks for considering,
  Lucas Kanashiro,
  Debian Perl Group

**Comment by mithun** [comment]
Fixed in 1.1.1
